# permissions for end users to edit mongodbroutes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: mongodbroute-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: gateway-api
    app.kubernetes.io/part-of: gateway-api
    app.kubernetes.io/managed-by: kustomize
  name: mongodbroute-editor-role
rules:
- apiGroups:
  - gateway.voyagermesh.com
  resources:
  - mongodbroutes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gateway.voyagermesh.com
  resources:
  - mongodbroutes/status
  verbs:
  - get
