# permissions for end users to view postgresroutes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: gateway-api
    app.kubernetes.io/managed-by: kustomize
  name: gateway-postgresroute-viewer-role
rules:
- apiGroups:
  - gateway.voyagermesh.com
  resources:
  - postgresroutes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gateway.voyagermesh.com
  resources:
  - postgresroutes/status
  verbs:
  - get
