# permissions for end users to edit kafkaroutes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: gateway-api
    app.kubernetes.io/managed-by: kustomize
  name: gateway-kafkaroute-editor-role
rules:
- apiGroups:
  - gateway.voyagermesh.com
  resources:
  - kafkaroutes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gateway.voyagermesh.com
  resources:
  - kafkaroutes/status
  verbs:
  - get
