apiVersion: gateway.voyagermesh.com/v1alpha1
kind: MongoDBRoute
metadata:
  labels:
    app.kubernetes.io/name: mongodbroute
    app.kubernetes.io/instance: mongodbroute-sample
    app.kubernetes.io/part-of: gateway-api
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: gateway-api
  name: mongodbroute-sample
spec:
  # TODO(user): Add fields here
